
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_7100000e70(L2CAgentBase *param_1)

{
  L2CValue aLStack64 [16];
  L2CValue aLStack48 [16];
  
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_N);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialN_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_N);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialN_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_N);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialN_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialS_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialS_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialS_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_THROW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSThrow_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_THROW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSThrow_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_THROW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSThrow_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_SHOULDER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSShoulder_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_SHOULDER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSShoulder_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_SHOULDER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSShoulder_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_LARIAT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSLariat_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_LARIAT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSLariat_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_LARIAT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSLariat_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_FAILURE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSFailure_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_FAILURE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSFailure_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_FAILURE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSFailure_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSEnd_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_S_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialSEnd_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHi_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHi_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHi_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiTurn_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_TURN);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiTurn_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiTurn_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_FALL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiFall_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_FALL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiFall_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_FALL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiFall_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiLoop_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiLoop_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiLoop_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiEnd_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiEnd_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_BOUND);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_BOUND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_BOUND);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_CHECK_ATTACK);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_check_atk);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_CHECK_ATTACK);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_check_atk);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_FALL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_CHECK_ATTACK);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_check_atk);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_CHECK_ATTACK);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_check_atk);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_CHECK_ATTACK);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_check_atk);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_HI_BOUND);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_CHECK_ATTACK);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialHiBound_check_atk);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLw_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLw_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLw_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLwHit_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLwHit_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLwHit_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_LW_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLwTurn_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_LW_TURN);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLwTurn_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_SPECIAL_LW_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::SpecialLwTurn_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::Final_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::Final_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::Final_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_DASH);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalDash_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_DASH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalDash_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_DASH);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalDash_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_DASH_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalDashEnd_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_DASH_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalDashEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_DASH_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalDashEnd_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_READY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalReady_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_READY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalReady_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_READY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalReady_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE01);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene01_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE01);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene01_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE01);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene01_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE02);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene02_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE02);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene02_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE02);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene02_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE03);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene03_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE03);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene03_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_SCENE03);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalScene03_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalEnd_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GAOGAEN_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::FinalEnd_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::Attack_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_ATTACK_DASH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::AttackDash_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_ATTACK_S4);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::AttackS4_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_ATTACK_HI4);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::AttackHi4_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_ATTACK_LW4);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::AttackLw4_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_THROW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGaogaen::status::Throw_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  return;
}

