
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_7100001e30(L2CAgentBase *param_1)

{
  L2CValue aLStack64 [16];
  L2CValue aLStack48 [16];
  
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_N);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialN_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_N);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialN_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_N);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialN_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialS_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialS_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialS_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHi_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHi_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHi_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialLw_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialLw_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialLw_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::Final_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::Final_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::Final_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_S_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialSPartner_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_S_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialSPartner_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_S_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialSPartner_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_FAIL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiFail_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_FAIL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiFail_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_FAIL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiFail_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP_PRE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJumpPre_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP_PRE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJumpPre_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP_PRE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJumpPre_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiPartner_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiPartner_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiPartner_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJumpPartner_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJumpPartner_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJumpPartner_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJump_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJump_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJump_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_COMP_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffCompPartner_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_COMP_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffCompPartner_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_COMP_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffCompPartner_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_PULL_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffPullPartner_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_PULL_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffPullPartner_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_PULL_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffPullPartner_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_COMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffComp_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_COMP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffComp_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_CLIFF_COMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiCliffComp_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_FINAL_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::FinalPartner_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_FINAL_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::FinalPartner_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_FINAL_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::FinalPartner_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_FINAL_HANG);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::FinalHang_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_FINAL_HANG);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::FinalHang_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_FINAL_HANG);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::FinalHang_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_CAPTURE_PANIC_NANA);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::CapturePanicNana_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_CAPTURE_PANIC_NANA);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::CapturePanicNana_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_CAPTURE_PANIC_NANA);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::CapturePanicNana_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_THROW_NANA);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::ThrowNana_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_THROW_NANA);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::ThrowNana_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_THROW_NANA);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::ThrowNana_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_CHEER_NANA);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::CheerNana_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_CHEER_NANA);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::CheerNana_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_CHEER_NANA);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::CheerNana_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_POPO_STATUS_KIND_SPECIAL_HI_JUMP_PARTNER);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_CALC_PARAM);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterPopo::status::SpecialHiJumpPartner_calc_param);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  return;
}

