
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __thiscall FUN_710000cd80(L2CFighterMiifighter *this,L2CValue *return_value)

{
  byte bVar1;
  bool bVar2;
  int iVar3;
  ulong uVar4;
  ulong uVar5;
  BattleObjectModuleAccessor **ppBVar6;
  float fVar7;
  L2CValue aLStack560 [16];
  L2CValue aLStack544 [16];
  L2CValue aLStack528 [16];
  L2CValue aLStack512 [16];
  L2CValue aLStack496 [16];
  L2CValue aLStack480 [16];
  L2CValue aLStack464 [16];
  L2CValue aLStack448 [16];
  L2CValue aLStack432 [16];
  L2CValue aLStack416 [16];
  L2CValue aLStack400 [16];
  L2CValue aLStack384 [16];
  L2CValue aLStack368 [16];
  L2CValue aLStack352 [16];
  L2CValue aLStack336 [16];
  L2CValue aLStack320 [16];
  L2CValue aLStack304 [16];
  L2CValue aLStack288 [16];
  L2CValue aLStack272 [16];
  L2CValue aLStack256 [16];
  L2CValue aLStack240 [16];
  L2CValue aLStack224 [16];
  L2CValue aLStack208 [16];
  L2CValue aLStack192 [16];
  L2CValue aLStack176 [16];
  L2CValue aLStack160 [16];
  L2CValue aLStack144 [16];
  L2CValue aLStack128 [16];
  L2CValue aLStack112 [16];
  L2CValue aLStack96 [16];
  L2CValue aLStack80 [16];
  
  lib::L2CValue::L2CValue(aLStack96,0);
  lib::L2CValue::L2CValue(aLStack112,0);
  lib::L2CValue::L2CValue(aLStack128,0);
  lib::L2CValue::L2CValue(aLStack144,0);
  lib::L2CValue::L2CValue(aLStack160,0);
  lib::L2CValue::L2CValue(aLStack176,0);
  lib::L2CValue::L2CValue(aLStack192,0);
  lib::L2CValue::L2CValue(aLStack208,0);
  lib::L2CValue::L2CValue(aLStack224,0);
  lib::L2CValue::L2CValue(aLStack240,0);
  lib::L2CValue::L2CValue(aLStack256,0);
  lib::L2CValue::L2CValue(aLStack272,0);
  lib::L2CValue::L2CValue(aLStack288,0);
  lib::L2CValue::L2CValue(aLStack304,0);
  lib::L2CValue::L2CValue(aLStack320,0);
  lib::L2CValue::L2CValue(aLStack336,0);
  lib::L2CValue::L2CValue(aLStack352,0);
  lib::L2CValue::L2CValue(aLStack368,0);
  lib::L2CValue::L2CValue(aLStack384,0);
  lib::L2CValue::L2CValue(aLStack400,0);
  lib::L2CValue::L2CValue
            (aLStack432,_FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_START_MODIFY);
  iVar3 = lib::L2CValue::as_integer(aLStack432);
  ppBVar6 = &this->moduleAccessor;
  bVar1 = app::lua_bind::WorkModule__is_flag_impl(*ppBVar6,iVar3);
  lib::L2CValue::L2CValue(aLStack416,(bool)(bVar1 & 1));
  lib::L2CValue::L2CValue(aLStack80,false);
  uVar4 = lib::L2CValue::operator==(aLStack416,aLStack80);
  lib::L2CValue::~L2CValue(aLStack80);
  lib::L2CValue::~L2CValue(aLStack416);
  lib::L2CValue::~L2CValue(aLStack432);
  if ((uVar4 & 1) == 0) {
    lib::L2CValue::L2CValue
              (aLStack416,_FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_BRAKE_TRIGGER);
    iVar3 = lib::L2CValue::as_integer(aLStack416);
    bVar1 = app::lua_bind::WorkModule__is_flag_impl(*ppBVar6,iVar3);
    lib::L2CValue::L2CValue(aLStack80,(bool)(bVar1 & 1));
    bVar2 = lib::L2CValue::operator.cast.to.bool(aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack416);
    if ((bVar2 & 1U) != 0) {
      lib::L2CValue::L2CValue(aLStack80,0xfea97fe73);
      lib::L2CValue::L2CValue(aLStack432,0xfda81b0ff);
      uVar4 = lib::L2CValue::as_integer(aLStack80);
      uVar5 = lib::L2CValue::as_integer(aLStack432);
      fVar7 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar6,uVar4,uVar5);
      lib::L2CValue::L2CValue(aLStack416,fVar7);
      lib::L2CValue::~L2CValue(aLStack432);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::L2CValue(aLStack80,0xfea97fe73);
      lib::L2CValue::L2CValue(aLStack448,0x133649edb7);
      uVar4 = lib::L2CValue::as_integer(aLStack80);
      uVar5 = lib::L2CValue::as_integer(aLStack448);
      fVar7 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar6,uVar4,uVar5);
      lib::L2CValue::L2CValue(aLStack432,fVar7);
      lib::L2CValue::~L2CValue(aLStack448);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
      lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
      fVar7 = (float)app::sv_kinetic_energy::get_speed_x(this->luaStateAgent);
      lib::L2CValue::L2CValue(aLStack448,fVar7);
      lib::L2CValue::~L2CValue(aLStack80);
      fVar7 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar6);
      lib::L2CValue::L2CValue(aLStack464,fVar7);
      lib::L2CValue::L2CValue(aLStack80,0.0);
      uVar4 = lib::L2CValue::operator<(aLStack80,aLStack464);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::~L2CValue(aLStack464);
      if ((uVar4 & 1) == 0) {
        lib::L2CValue::operator+(aLStack448,aLStack416);
        lib::L2CValue::operator-(aLStack432);
        uVar4 = lib::L2CValue::operator<=(aLStack464,aLStack80);
        lib::L2CValue::~L2CValue(aLStack464);
        lib::L2CValue::~L2CValue(aLStack80);
        if ((uVar4 & 1) != 0) {
          lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::operator-(aLStack432);
          lib::L2CValue::L2CValue(aLStack480,0.0);
          lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack480);
          app::sv_kinetic_energy::set_speed(this->luaStateAgent);
          lib::L2CValue::~L2CValue(aLStack480);
          lib::L2CValue::~L2CValue(aLStack464);
          lib::L2CValue::~L2CValue(aLStack80);
          lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack464,0.0);
          lib::L2CValue::L2CValue(aLStack480,0.0);
          lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack480);
          app::sv_kinetic_energy::set_brake(this->luaStateAgent);
          goto LAB_7100016648;
        }
        lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
        lib::L2CValue::L2CValue(aLStack464,0.0);
        lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
        lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
        lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack416);
        lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
        app::sv_kinetic_energy::set_brake(this->luaStateAgent);
      }
      else {
        lib::L2CValue::operator-(aLStack448,aLStack416);
        uVar4 = lib::L2CValue::operator<=(aLStack80,aLStack432);
        lib::L2CValue::~L2CValue(aLStack80);
        if ((uVar4 & 1) == 0) {
          lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack464,0.0);
          lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack416);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
          app::sv_kinetic_energy::set_brake(this->luaStateAgent);
        }
        else {
          lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack464,0.0);
          lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack432);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
          app::sv_kinetic_energy::set_speed(this->luaStateAgent);
          lib::L2CValue::~L2CValue(aLStack464);
          lib::L2CValue::~L2CValue(aLStack80);
          lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack464,0.0);
          lib::L2CValue::L2CValue(aLStack480,0.0);
          lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
          lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack480);
          app::sv_kinetic_energy::set_brake(this->luaStateAgent);
LAB_7100016648:
          lib::L2CValue::~L2CValue(aLStack480);
        }
      }
      lib::L2CValue::~L2CValue(aLStack464);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::~L2CValue(aLStack448);
      lib::L2CValue::~L2CValue(aLStack432);
      lib::L2CValue::~L2CValue(aLStack416);
    }
    lib::L2CValue::L2CValue(aLStack416,0xfea97fe73);
    lib::L2CValue::L2CValue(aLStack432,0xd2a42eb24);
    uVar4 = lib::L2CValue::as_integer(aLStack416);
    uVar5 = lib::L2CValue::as_integer(aLStack432);
    fVar7 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar6,uVar4,uVar5);
    lib::L2CValue::L2CValue(aLStack80,fVar7);
    lib::L2CValue::operator=(aLStack112,aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::L2CValue(aLStack416,0xfea97fe73);
    lib::L2CValue::L2CValue(aLStack432,0xd5e94c502);
    uVar4 = lib::L2CValue::as_integer(aLStack416);
    uVar5 = lib::L2CValue::as_integer(aLStack432);
    fVar7 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar6,uVar4,uVar5);
    lib::L2CValue::L2CValue(aLStack80,fVar7);
    lib::L2CValue::operator=(aLStack96,aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::L2CValue(aLStack80,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
    lib::L2CValue::operator-(aLStack112);
    lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack416);
    app::sv_kinetic_energy::set_accel(this->luaStateAgent);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue(aLStack80,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
    lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack96);
    app::sv_kinetic_energy::set_limit_speed(this->luaStateAgent);
  }
  else {
    lib::L2CValue::L2CValue
              (aLStack416,_FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_START);
    iVar3 = lib::L2CValue::as_integer(aLStack416);
    bVar1 = app::lua_bind::WorkModule__is_flag_impl(*ppBVar6,iVar3);
    lib::L2CValue::L2CValue(aLStack80,(bool)(bVar1 & 1));
    bVar2 = lib::L2CValue::operator.cast.to.bool(aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack416);
    if ((bVar2 & 1U) == 0) goto LAB_7100016894;
    lib::L2CValue::L2CValue(aLStack416,0xfea97fe73);
    lib::L2CValue::L2CValue(aLStack432,0xd0bdab699);
    uVar4 = lib::L2CValue::as_integer(aLStack416);
    uVar5 = lib::L2CValue::as_integer(aLStack432);
    fVar7 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar6,uVar4,uVar5);
    lib::L2CValue::L2CValue(aLStack80,fVar7);
    lib::L2CValue::operator=(aLStack144,aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::operator=(aLStack256,aLStack144);
    fVar7 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar6);
    lib::L2CValue::L2CValue(aLStack416,fVar7);
    lib::L2CValue::operator*(aLStack256,aLStack416);
    lib::L2CValue::operator=(aLStack256,aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
    lib::L2CValue::L2CValue(aLStack416,_ENERGY_STOP_RESET_TYPE_FREE);
    lib::L2CValue::L2CValue(aLStack432,0.0);
    lib::L2CValue::L2CValue(aLStack448,0.0);
    lib::L2CValue::L2CValue(aLStack464,0.0);
    lib::L2CValue::L2CValue(aLStack480,0.0);
    lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack416);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack256);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack432);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack448);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack480);
    app::sv_kinetic_energy::reset_energy(this->luaStateAgent);
    lib::L2CValue::~L2CValue(aLStack480);
    lib::L2CValue::~L2CValue(aLStack464);
    lib::L2CValue::~L2CValue(aLStack448);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_STOP);
    iVar3 = lib::L2CValue::as_integer(aLStack80);
    app::lua_bind::KineticModule__enable_energy_impl(*ppBVar6,iVar3);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue(aLStack416,0xfea97fe73);
    lib::L2CValue::L2CValue(aLStack432,0x113ceef50b);
    uVar4 = lib::L2CValue::as_integer(aLStack416);
    uVar5 = lib::L2CValue::as_integer(aLStack432);
    fVar7 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar6,uVar4,uVar5);
    lib::L2CValue::L2CValue(aLStack80,fVar7);
    lib::L2CValue::operator=(aLStack272,aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::L2CValue(aLStack432,0xfea97fe73);
    lib::L2CValue::L2CValue(aLStack448,0x1100e3ca52);
    uVar4 = lib::L2CValue::as_integer(aLStack432);
    uVar5 = lib::L2CValue::as_integer(aLStack448);
    fVar7 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar6,uVar4,uVar5);
    lib::L2CValue::L2CValue(aLStack416,fVar7);
    lib::L2CValue::operator-(aLStack416,aLStack272);
    lib::L2CValue::operator=(aLStack320,aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::~L2CValue(aLStack448);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::operator=(aLStack176,aLStack272);
    lib::L2CValue::L2CValue(aLStack80,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
    lib::L2CValue::L2CValue(aLStack416,_ENERGY_GRAVITY_RESET_TYPE_GRAVITY);
    lib::L2CValue::L2CValue(aLStack432,0.0);
    lib::L2CValue::L2CValue(aLStack448,0.0);
    lib::L2CValue::L2CValue(aLStack464,0.0);
    lib::L2CValue::L2CValue(aLStack480,0.0);
    lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack416);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack432);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack176);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack448);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack480);
    app::sv_kinetic_energy::reset_energy(this->luaStateAgent);
    lib::L2CValue::~L2CValue(aLStack480);
    lib::L2CValue::~L2CValue(aLStack464);
    lib::L2CValue::~L2CValue(aLStack448);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue(aLStack80,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
    iVar3 = lib::L2CValue::as_integer(aLStack80);
    app::lua_bind::KineticModule__enable_energy_impl(*ppBVar6,iVar3);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_CONTROL);
    lib::L2CValue::L2CValue(aLStack416,_ENERGY_CONTROLLER_RESET_TYPE_FREE);
    lib::L2CValue::L2CValue(aLStack432,0.0);
    lib::L2CValue::L2CValue(aLStack448,0.0);
    lib::L2CValue::L2CValue(aLStack464,0.0);
    lib::L2CValue::L2CValue(aLStack480,0.0);
    lib::L2CValue::L2CValue(aLStack496,0.0);
    lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack416);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack432);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack448);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack480);
    lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack496);
    app::sv_kinetic_energy::reset_energy(this->luaStateAgent);
    lib::L2CValue::~L2CValue(aLStack496);
    lib::L2CValue::~L2CValue(aLStack480);
    lib::L2CValue::~L2CValue(aLStack464);
    lib::L2CValue::~L2CValue(aLStack448);
    lib::L2CValue::~L2CValue(aLStack432);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue(aLStack80,_FIGHTER_KINETIC_ENERGY_ID_CONTROL);
    iVar3 = lib::L2CValue::as_integer(aLStack80);
    app::lua_bind::KineticModule__unable_energy_impl(*ppBVar6,iVar3);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue
              (aLStack80,_FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_START);
    iVar3 = lib::L2CValue::as_integer(aLStack80);
    app::lua_bind::WorkModule__off_flag_impl(*ppBVar6,iVar3);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::L2CValue
              (aLStack80,_FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_START_MODIFY);
    iVar3 = lib::L2CValue::as_integer(aLStack80);
    app::lua_bind::WorkModule__on_flag_impl(*ppBVar6,iVar3);
  }
  lib::L2CValue::~L2CValue(aLStack80);
LAB_7100016894:
  lib::L2CValue::L2CValue
            (aLStack416,
             _FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_DROPKICK_AURA_EFFECT_ON);
  iVar3 = lib::L2CValue::as_integer(aLStack416);
  bVar1 = app::lua_bind::WorkModule__is_flag_impl(*ppBVar6,iVar3);
  lib::L2CValue::L2CValue(aLStack80,(bool)(bVar1 & 1));
  bVar2 = lib::L2CValue::operator.cast.to.bool(aLStack80);
  lib::L2CValue::~L2CValue(aLStack80);
  lib::L2CValue::~L2CValue(aLStack416);
  if ((bVar2 & 1U) != 0) {
    lib::L2CValue::L2CValue
              (aLStack432,
               _FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_DROPKICK_AURA_EFFECT);
    iVar3 = lib::L2CValue::as_integer(aLStack432);
    bVar1 = app::lua_bind::WorkModule__is_flag_impl(*ppBVar6,iVar3);
    lib::L2CValue::L2CValue(aLStack416,(bool)(bVar1 & 1));
    lib::L2CValue::L2CValue(aLStack80,false);
    uVar4 = lib::L2CValue::operator==(aLStack416,aLStack80);
    lib::L2CValue::~L2CValue(aLStack80);
    lib::L2CValue::~L2CValue(aLStack416);
    lib::L2CValue::~L2CValue(aLStack432);
    if ((uVar4 & 1) != 0) {
      lib::L2CValue::L2CValue(aLStack80,0.0);
      lib::L2CValue::operator=(aLStack352,aLStack80);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::L2CValue(aLStack80,0x1a8ce93360);
      lib::L2CValue::operator=(aLStack336,aLStack80);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::L2CValue(aLStack80,0.8);
      lib::L2CValue::operator=(aLStack224,aLStack80);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::L2CValue(aLStack80,_MA_MSC_CMD_EFFECT_EFFECT_FOLLOW_ALPHA);
      lib::L2CValue::L2CValue(aLStack416,0x35dbfe258);
      lib::L2CValue::L2CValue(aLStack432,-10.0);
      lib::L2CValue::L2CValue(aLStack448,0.0);
      lib::L2CValue::L2CValue(aLStack464,0.0);
      lib::L2CValue::L2CValue(aLStack480,0.0);
      lib::L2CValue::L2CValue(aLStack496,0.0);
      lib::L2CValue::L2CValue(aLStack528,90.0);
      lib::L2CValue::L2CValue(aLStack544,1.0);
      lib::L2CValue::L2CValue(aLStack560,true);
      lib::L2CAgent::clear_lua_stack((L2CAgent *)this);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack80);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack336);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack416);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack432);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack448);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack464);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack480);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack496);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack528);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack544);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack560);
      lib::L2CAgent::push_lua_stack((L2CAgent *)this,aLStack224);
      app::sv_module_access::effect(this->luaStateAgent);
      lib::L2CAgent::pop_lua_stack((L2CAgent *)this,1);
      lib::L2CValue::~L2CValue(aLStack512);
      lib::L2CValue::~L2CValue(aLStack560);
      lib::L2CValue::~L2CValue(aLStack544);
      lib::L2CValue::~L2CValue(aLStack528);
      lib::L2CValue::~L2CValue(aLStack496);
      lib::L2CValue::~L2CValue(aLStack480);
      lib::L2CValue::~L2CValue(aLStack464);
      lib::L2CValue::~L2CValue(aLStack448);
      lib::L2CValue::~L2CValue(aLStack432);
      lib::L2CValue::~L2CValue(aLStack416);
      lib::L2CValue::~L2CValue(aLStack80);
      lib::L2CValue::L2CValue
                (aLStack80,
                 _FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_DROPKICK_AURA_EFFECT);
      iVar3 = lib::L2CValue::as_integer(aLStack80);
      app::lua_bind::WorkModule__on_flag_impl(*ppBVar6,iVar3);
      lib::L2CValue::~L2CValue(aLStack80);
    }
    lib::L2CValue::L2CValue
              (aLStack80,
               _FIGHTER_MIIFIGHTER_STATUS_WORK_ID_FLAG_NENSYO_KICK_MOVE_DROPKICK_AURA_EFFECT_ON);
    iVar3 = lib::L2CValue::as_integer(aLStack80);
    app::lua_bind::WorkModule__off_flag_impl(*ppBVar6,iVar3);
    lib::L2CValue::~L2CValue(aLStack80);
  }
  lib::L2CValue::L2CValue((L2CValue *)return_value,0);
  lib::L2CValue::~L2CValue(aLStack400);
  lib::L2CValue::~L2CValue(aLStack384);
  lib::L2CValue::~L2CValue(aLStack368);
  lib::L2CValue::~L2CValue(aLStack352);
  lib::L2CValue::~L2CValue(aLStack336);
  lib::L2CValue::~L2CValue(aLStack320);
  lib::L2CValue::~L2CValue(aLStack304);
  lib::L2CValue::~L2CValue(aLStack288);
  lib::L2CValue::~L2CValue(aLStack272);
  lib::L2CValue::~L2CValue(aLStack256);
  lib::L2CValue::~L2CValue(aLStack240);
  lib::L2CValue::~L2CValue(aLStack224);
  lib::L2CValue::~L2CValue(aLStack208);
  lib::L2CValue::~L2CValue(aLStack192);
  lib::L2CValue::~L2CValue(aLStack176);
  lib::L2CValue::~L2CValue(aLStack160);
  lib::L2CValue::~L2CValue(aLStack144);
  lib::L2CValue::~L2CValue(aLStack128);
  lib::L2CValue::~L2CValue(aLStack112);
  lib::L2CValue::~L2CValue(aLStack96);
  return;
}

