
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_71000024c0(L2CAgentBase *param_1)

{
  L2CValue aLStack64 [16];
  L2CValue aLStack48 [16];
  
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHi_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHi_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHi_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHiLoop_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHiLoop_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHiLoop_exec_stop);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_LOOP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHiEnd_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHiEnd_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHiEnd_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_WALL_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialHiWallDamage_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_WALL_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_WALL_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_WALL_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_WALL_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_HI_WALL_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialNMaxShot_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_SHOT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_SHOT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_MAX_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialNMaxShot_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_MAX_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_MAX_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_MAX_SHOT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_MAX_SHOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_N_MAX_SHOT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLw_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLw_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLw_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwHit_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwHit_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_HIT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwAttack_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwAttack_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwAttack_exec_stop);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwEnd_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwEnd_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwLanding_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_LANDING);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_LANDING);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_BOUND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialLwBound_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_BOUND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_BOUND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_BOUND);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_BOUND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_SPECIAL_LW_BOUND);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialS_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::SpecialS_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_EXEC_STOP);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_MAP_CORRECTION);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_GEKKOUGA_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_FIX_CAMERA);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterGekkouga::status::FinalEnd_fix_cam);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  return;
}

