
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_710000bdf0(L2CAgent *param_1)

{
  BattleObject **ppBVar1;
  byte bVar2;
  bool bVar3;
  int iVar4;
  int iVar5;
  GroundCorrectKind GVar6;
  ulong uVar7;
  ulong uVar8;
  L2CValue *pLVar9;
  BattleObjectModuleAccessor *pBVar10;
  BattleObjectModuleAccessor **ppBVar11;
  float fVar12;
  L2CValue aLStack288 [16];
  L2CValue aLStack272 [16];
  L2CValue aLStack256 [16];
  L2CValue aLStack240 [16];
  L2CValue aLStack224 [16];
  L2CValue aLStack208 [16];
  L2CValue aLStack192 [16];
  L2CValue aLStack176 [16];
  L2CValue aLStack160 [16];
  L2CValue aLStack144 [16];
  L2CValue aLStack128 [16];
  L2CValue aLStack112 [16];
  L2CValue aLStack96 [16];
  
  lib::L2CValue::L2CValue(aLStack224,0);
  lib::L2CValue::L2CValue(aLStack240,0);
  lib::L2CValue::L2CValue(aLStack256,0);
  lib::L2CValue::L2CValue(aLStack112,_FIGHTER_FOX_ILLUSION_STATUS_WORK_ID_INT_STEP);
  iVar4 = lib::L2CValue::as_integer(aLStack112);
  ppBVar11 = &param_1->moduleAccessor;
  iVar4 = app::lua_bind::WorkModule__get_int_impl(*ppBVar11,iVar4);
  lib::L2CValue::L2CValue(aLStack96,iVar4);
  lib::L2CValue::operator=(aLStack256,aLStack96);
  lib::L2CValue::~L2CValue(aLStack96);
  lib::L2CValue::~L2CValue(aLStack112);
  lib::L2CValue::L2CValue(aLStack96,_FIGHTER_FOX_ILLUSION_STATUS_WORK_ID_INT_STEP_PREV);
  iVar4 = lib::L2CValue::as_integer(aLStack256);
  iVar5 = lib::L2CValue::as_integer(aLStack96);
  app::lua_bind::WorkModule__set_int_impl(*ppBVar11,iVar4,iVar5);
  lib::L2CValue::~L2CValue(aLStack96);
  lib::L2CValue::L2CValue(aLStack96,_FIGHTER_FOX_ILLUSION_STEP_START);
  uVar7 = lib::L2CValue::operator==(aLStack256,aLStack96);
  lib::L2CValue::~L2CValue(aLStack96);
  if ((uVar7 & 1) == 0) {
    lib::L2CValue::L2CValue(aLStack96,_FIGHTER_FOX_ILLUSION_STEP_RUSH);
    uVar7 = lib::L2CValue::operator==(aLStack256,aLStack96);
    lib::L2CValue::~L2CValue(aLStack96);
    if ((uVar7 & 1) == 0) {
      lib::L2CValue::L2CValue(aLStack96,_FIGHTER_FOX_ILLUSION_STEP_END);
      uVar7 = lib::L2CValue::operator==(aLStack256,aLStack96);
      lib::L2CValue::~L2CValue(aLStack96);
      if ((uVar7 & 1) == 0) goto LAB_710000c848;
      ppBVar1 = &param_1[2].battleObject;
      pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,2);
      lib::L2CValue::L2CValue(aLStack96,FIGHTER_KIND_WOLF);
      uVar7 = lib::L2CValue::operator==(pLVar9,aLStack96);
      lib::L2CValue::~L2CValue(aLStack96);
      if ((uVar7 & 1) == 0) {
        lib::L2CValue::L2CValue(aLStack288,false);
      }
      else {
        lib::L2CValue::L2CValue(aLStack96,0xfea97fe73);
        lib::L2CValue::L2CValue(aLStack128,0x1dea3f79e3);
        uVar7 = lib::L2CValue::as_integer(aLStack96);
        uVar8 = lib::L2CValue::as_integer(aLStack128);
        iVar4 = app::lua_bind::WorkModule__get_param_int_impl(*ppBVar11,uVar7,uVar8);
        lib::L2CValue::L2CValue(aLStack112,iVar4);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,_FIGHTER_FOX_ILLUSION_STATUS_WORK_ID_INT_STOP_Y_FRAME);
        iVar4 = lib::L2CValue::as_integer(aLStack112);
        iVar5 = lib::L2CValue::as_integer(aLStack96);
        app::lua_bind::WorkModule__set_int_impl(*ppBVar11,iVar4,iVar5);
        lib::L2CValue::~L2CValue(aLStack96);
        pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,0x16);
        lib::L2CValue::L2CValue(aLStack96,SITUATION_KIND_AIR);
        uVar7 = lib::L2CValue::operator==(pLVar9,aLStack96);
        lib::L2CValue::~L2CValue(aLStack96);
        if ((uVar7 & 1) == 0) {
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack144,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack160,0x14c622b36d);
          uVar7 = lib::L2CValue::as_integer(aLStack144);
          uVar8 = lib::L2CValue::as_integer(aLStack160);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack128,fVar12);
          lib::L2CValue::L2CValue(aLStack176,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack128);
          lib::L2CAgent::push_lua_stack(param_1,aLStack176);
          app::sv_kinetic_energy::set_brake(param_1->luaStateAgent);
          lib::L2CValue::~L2CValue(aLStack176);
          lib::L2CValue::~L2CValue(aLStack128);
          lib::L2CValue::~L2CValue(aLStack160);
          lib::L2CValue::~L2CValue(aLStack144);
          lib::L2CValue::~L2CValue(aLStack96);
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack160,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack176,0x145ede3ed8);
          uVar7 = lib::L2CValue::as_integer(aLStack160);
          uVar8 = lib::L2CValue::as_integer(aLStack176);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack144,fVar12);
          fVar12 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar11);
          lib::L2CValue::L2CValue(aLStack192,fVar12);
          lib::L2CValue::operator*(aLStack144,aLStack192);
          lib::L2CValue::L2CValue(aLStack208,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack128);
          lib::L2CAgent::push_lua_stack(param_1,aLStack208);
          app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        }
        else {
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack144,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack160,0x18fa60b2ca);
          uVar7 = lib::L2CValue::as_integer(aLStack144);
          uVar8 = lib::L2CValue::as_integer(aLStack160);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack128,fVar12);
          lib::L2CValue::L2CValue(aLStack176,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack128);
          lib::L2CAgent::push_lua_stack(param_1,aLStack176);
          app::sv_kinetic_energy::set_brake(param_1->luaStateAgent);
          lib::L2CValue::~L2CValue(aLStack176);
          lib::L2CValue::~L2CValue(aLStack128);
          lib::L2CValue::~L2CValue(aLStack160);
          lib::L2CValue::~L2CValue(aLStack144);
          lib::L2CValue::~L2CValue(aLStack96);
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack160,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack176,0x18629c3f7f);
          uVar7 = lib::L2CValue::as_integer(aLStack160);
          uVar8 = lib::L2CValue::as_integer(aLStack176);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack144,fVar12);
          fVar12 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar11);
          lib::L2CValue::L2CValue(aLStack192,fVar12);
          lib::L2CValue::operator*(aLStack144,aLStack192);
          lib::L2CValue::L2CValue(aLStack208,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack128);
          lib::L2CAgent::push_lua_stack(param_1,aLStack208);
          app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        }
        lib::L2CValue::~L2CValue(aLStack208);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack192);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack176);
        lib::L2CValue::~L2CValue(aLStack160);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
        lib::L2CValue::L2CValue(aLStack128,10.0);
        lib::L2CValue::L2CValue(aLStack144,10.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack128);
        lib::L2CAgent::push_lua_stack(param_1,aLStack144);
        app::sv_kinetic_energy::set_limit_speed(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
        iVar4 = lib::L2CValue::as_integer(aLStack96);
        app::lua_bind::KineticModule__enable_energy_impl(*ppBVar11,iVar4);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        lib::L2CValue::L2CValue(aLStack128,_ENERGY_GRAVITY_RESET_TYPE_GRAVITY);
        lib::L2CValue::L2CValue(aLStack144,0.0);
        lib::L2CValue::L2CValue(aLStack160,0.0);
        lib::L2CValue::L2CValue(aLStack176,0.0);
        lib::L2CValue::L2CValue(aLStack192,0.0);
        lib::L2CValue::L2CValue(aLStack208,0.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack128);
        lib::L2CAgent::push_lua_stack(param_1,aLStack144);
        lib::L2CAgent::push_lua_stack(param_1,aLStack160);
        lib::L2CAgent::push_lua_stack(param_1,aLStack176);
        lib::L2CAgent::push_lua_stack(param_1,aLStack192);
        lib::L2CAgent::push_lua_stack(param_1,aLStack208);
        app::sv_kinetic_energy::reset_energy(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack208);
        lib::L2CValue::~L2CValue(aLStack192);
        lib::L2CValue::~L2CValue(aLStack176);
        lib::L2CValue::~L2CValue(aLStack160);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        lib::L2CValue::L2CValue(aLStack144,0xfea97fe73);
        lib::L2CValue::L2CValue(aLStack160,0x1706468516);
        uVar7 = lib::L2CValue::as_integer(aLStack144);
        uVar8 = lib::L2CValue::as_integer(aLStack160);
        fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
        lib::L2CValue::L2CValue(aLStack128,fVar12);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack128);
        app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack160);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        lib::L2CValue::L2CValue(aLStack128,0.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack128);
        app::sv_kinetic_energy::set_accel(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        lib::L2CValue::L2CValue(aLStack128,10.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack128);
        app::sv_kinetic_energy::set_limit_speed(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        iVar4 = lib::L2CValue::as_integer(aLStack96);
        app::lua_bind::KineticModule__enable_energy_impl(*ppBVar11,iVar4);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_MOTION);
        pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,5);
        iVar4 = lib::L2CValue::as_integer(aLStack96);
        pBVar10 = (BattleObjectModuleAccessor *)lib::L2CValue::as_pointer(pLVar9);
        app::KineticUtility::clear_unable_energy(iVar4,pBVar10);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack288,true);
        lib::L2CValue::~L2CValue(aLStack112);
      }
      lib::L2CValue::L2CValue(aLStack96,false);
      uVar7 = lib::L2CValue::operator==(aLStack288,aLStack96);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::~L2CValue(aLStack288);
      if ((uVar7 & 1) == 0) goto LAB_710000c848;
      lib::L2CValue::L2CValue(aLStack112,0xfea97fe73);
      lib::L2CValue::L2CValue(aLStack128,0x1dea3f79e3);
      uVar7 = lib::L2CValue::as_integer(aLStack112);
      uVar8 = lib::L2CValue::as_integer(aLStack128);
      iVar4 = app::lua_bind::WorkModule__get_param_int_impl(*ppBVar11,uVar7,uVar8);
      lib::L2CValue::L2CValue(aLStack96,iVar4);
      lib::L2CValue::operator=(aLStack224,aLStack96);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::~L2CValue(aLStack128);
      lib::L2CValue::~L2CValue(aLStack112);
      lib::L2CValue::L2CValue(aLStack96,_FIGHTER_FOX_ILLUSION_STATUS_WORK_ID_INT_STOP_Y_FRAME);
      iVar4 = lib::L2CValue::as_integer(aLStack224);
      iVar5 = lib::L2CValue::as_integer(aLStack96);
      app::lua_bind::WorkModule__set_int_impl(*ppBVar11,iVar4,iVar5);
      lib::L2CValue::~L2CValue(aLStack96);
      pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,0x16);
      lib::L2CValue::L2CValue(aLStack96,SITUATION_KIND_AIR);
      uVar7 = lib::L2CValue::operator==(pLVar9,aLStack96);
      lib::L2CValue::~L2CValue(aLStack96);
      if ((uVar7 & 1) == 0) {
        lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
        lib::L2CValue::L2CValue(aLStack128,0xfea97fe73);
        lib::L2CValue::L2CValue(aLStack144,0x14c622b36d);
        uVar7 = lib::L2CValue::as_integer(aLStack128);
        uVar8 = lib::L2CValue::as_integer(aLStack144);
        fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
        lib::L2CValue::L2CValue(aLStack112,fVar12);
        lib::L2CValue::L2CValue(aLStack160,0.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack112);
        lib::L2CAgent::push_lua_stack(param_1,aLStack160);
        app::sv_kinetic_energy::set_brake(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack160);
        lib::L2CValue::~L2CValue(aLStack112);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack112,_FIGHTER_FOX_ILLUSION_STATUS_WORK_ID_FLAG_HIT_SHIELD);
        iVar4 = lib::L2CValue::as_integer(aLStack112);
        bVar2 = app::lua_bind::WorkModule__is_flag_impl(*ppBVar11,iVar4);
        lib::L2CValue::L2CValue(aLStack96,(bool)(bVar2 & 1));
        bVar3 = lib::L2CValue::operator.cast.to.bool(aLStack96);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::~L2CValue(aLStack112);
        if ((bVar3 & 1U) == 0) {
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack144,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack160,0x145ede3ed8);
          uVar7 = lib::L2CValue::as_integer(aLStack144);
          uVar8 = lib::L2CValue::as_integer(aLStack160);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack128,fVar12);
          fVar12 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar11);
          lib::L2CValue::L2CValue(aLStack176,fVar12);
          lib::L2CValue::operator*(aLStack128,aLStack176);
          lib::L2CValue::L2CValue(aLStack192,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack112);
          lib::L2CAgent::push_lua_stack(param_1,aLStack192);
          app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        }
        else {
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack144,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack160,0x1fe9ba9514);
          uVar7 = lib::L2CValue::as_integer(aLStack144);
          uVar8 = lib::L2CValue::as_integer(aLStack160);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack128,fVar12);
          fVar12 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar11);
          lib::L2CValue::L2CValue(aLStack176,fVar12);
          lib::L2CValue::operator*(aLStack128,aLStack176);
          lib::L2CValue::L2CValue(aLStack192,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack112);
          lib::L2CAgent::push_lua_stack(param_1,aLStack192);
          app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        }
        lib::L2CValue::~L2CValue(aLStack192);
        lib::L2CValue::~L2CValue(aLStack112);
        lib::L2CValue::~L2CValue(aLStack176);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack160);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
        iVar4 = lib::L2CValue::as_integer(aLStack96);
        app::lua_bind::KineticModule__enable_energy_impl(*ppBVar11,iVar4);
      }
      else {
        lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
        lib::L2CValue::L2CValue(aLStack128,0xfea97fe73);
        lib::L2CValue::L2CValue(aLStack144,0x18fa60b2ca);
        uVar7 = lib::L2CValue::as_integer(aLStack128);
        uVar8 = lib::L2CValue::as_integer(aLStack144);
        fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
        lib::L2CValue::L2CValue(aLStack112,fVar12);
        lib::L2CValue::L2CValue(aLStack160,0.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack112);
        lib::L2CAgent::push_lua_stack(param_1,aLStack160);
        app::sv_kinetic_energy::set_brake(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack160);
        lib::L2CValue::~L2CValue(aLStack112);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack112,_FIGHTER_FOX_ILLUSION_STATUS_WORK_ID_FLAG_HIT_SHIELD);
        iVar4 = lib::L2CValue::as_integer(aLStack112);
        bVar2 = app::lua_bind::WorkModule__is_flag_impl(*ppBVar11,iVar4);
        lib::L2CValue::L2CValue(aLStack96,(bool)(bVar2 & 1));
        bVar3 = lib::L2CValue::operator.cast.to.bool(aLStack96);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::~L2CValue(aLStack112);
        if ((bVar3 & 1U) == 0) {
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack144,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack160,0x18629c3f7f);
          uVar7 = lib::L2CValue::as_integer(aLStack144);
          uVar8 = lib::L2CValue::as_integer(aLStack160);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack128,fVar12);
          fVar12 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar11);
          lib::L2CValue::L2CValue(aLStack176,fVar12);
          lib::L2CValue::operator*(aLStack128,aLStack176);
          lib::L2CValue::L2CValue(aLStack192,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack112);
          lib::L2CAgent::push_lua_stack(param_1,aLStack192);
          app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        }
        else {
          lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
          lib::L2CValue::L2CValue(aLStack144,0xfea97fe73);
          lib::L2CValue::L2CValue(aLStack160,0x23dfbe54cc);
          uVar7 = lib::L2CValue::as_integer(aLStack144);
          uVar8 = lib::L2CValue::as_integer(aLStack160);
          fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
          lib::L2CValue::L2CValue(aLStack128,fVar12);
          fVar12 = (float)app::lua_bind::PostureModule__lr_impl(*ppBVar11);
          lib::L2CValue::L2CValue(aLStack176,fVar12);
          lib::L2CValue::operator*(aLStack128,aLStack176);
          lib::L2CValue::L2CValue(aLStack192,0.0);
          lib::L2CAgent::clear_lua_stack(param_1);
          lib::L2CAgent::push_lua_stack(param_1,aLStack96);
          lib::L2CAgent::push_lua_stack(param_1,aLStack112);
          lib::L2CAgent::push_lua_stack(param_1,aLStack192);
          app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        }
        lib::L2CValue::~L2CValue(aLStack192);
        lib::L2CValue::~L2CValue(aLStack112);
        lib::L2CValue::~L2CValue(aLStack176);
        lib::L2CValue::~L2CValue(aLStack128);
        lib::L2CValue::~L2CValue(aLStack160);
        lib::L2CValue::~L2CValue(aLStack144);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
        iVar4 = lib::L2CValue::as_integer(aLStack96);
        app::lua_bind::KineticModule__enable_energy_impl(*ppBVar11,iVar4);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        lib::L2CValue::L2CValue(aLStack112,0.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack112);
        app::sv_kinetic_energy::set_accel(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack112);
      }
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
      lib::L2CValue::L2CValue(aLStack112,10.0);
      lib::L2CValue::L2CValue(aLStack128,10.0);
      lib::L2CAgent::clear_lua_stack(param_1);
      lib::L2CAgent::push_lua_stack(param_1,aLStack96);
      lib::L2CAgent::push_lua_stack(param_1,aLStack112);
      lib::L2CAgent::push_lua_stack(param_1,aLStack128);
      app::sv_kinetic_energy::set_limit_speed(param_1->luaStateAgent);
      lib::L2CValue::~L2CValue(aLStack128);
      lib::L2CValue::~L2CValue(aLStack112);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_MOTION);
      pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,5);
      iVar4 = lib::L2CValue::as_integer(aLStack96);
      pBVar10 = (BattleObjectModuleAccessor *)lib::L2CValue::as_pointer(pLVar9);
      app::KineticUtility::clear_unable_energy(iVar4,pBVar10);
      goto LAB_710000c82c;
    }
    pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)&param_1[2].battleObject,2);
    lib::L2CValue::L2CValue(aLStack96,FIGHTER_KIND_WOLF);
    uVar7 = lib::L2CValue::operator==(pLVar9,aLStack96);
    lib::L2CValue::~L2CValue(aLStack96);
    if ((uVar7 & 1) == 0) {
      lib::L2CValue::L2CValue(aLStack272,false);
    }
    else {
      lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_TYPE_FALL._4_4_);
      GVar6 = lib::L2CValue::as_integer(aLStack96);
      app::lua_bind::GroundModule__correct_impl(*ppBVar11,GVar6);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::L2CValue(aLStack272,true);
    }
    pLVar9 = aLStack272;
  }
  else {
    lib::L2CValue::L2CValue(aLStack112,0xfea97fe73);
    lib::L2CValue::L2CValue(aLStack128,0x15d86ad648);
    uVar7 = lib::L2CValue::as_integer(aLStack112);
    uVar8 = lib::L2CValue::as_integer(aLStack128);
    iVar4 = app::lua_bind::WorkModule__get_param_int_impl(*ppBVar11,uVar7,uVar8);
    lib::L2CValue::L2CValue(aLStack96,iVar4);
    lib::L2CValue::operator=(aLStack224,aLStack96);
    lib::L2CValue::~L2CValue(aLStack96);
    lib::L2CValue::~L2CValue(aLStack128);
    lib::L2CValue::~L2CValue(aLStack112);
    lib::L2CValue::L2CValue(aLStack96,_FIGHTER_FOX_ILLUSION_STATUS_WORK_ID_INT_STOP_Y_FRAME);
    iVar4 = lib::L2CValue::as_integer(aLStack224);
    iVar5 = lib::L2CValue::as_integer(aLStack96);
    app::lua_bind::WorkModule__set_int_impl(*ppBVar11,iVar4,iVar5);
    lib::L2CValue::~L2CValue(aLStack96);
    lib::L2CValue::L2CValue(aLStack112,_KINETIC_ENERGY_RESERVE_ATTRIBUTE_MAIN);
    iVar4 = lib::L2CValue::as_integer(aLStack112);
    fVar12 = (float)app::lua_bind::KineticModule__get_sum_speed_x_impl(*ppBVar11,iVar4);
    lib::L2CValue::L2CValue(aLStack96,fVar12);
    lib::L2CValue::operator=(aLStack240,aLStack96);
    lib::L2CValue::~L2CValue(aLStack96);
    lib::L2CValue::~L2CValue(aLStack112);
    lib::L2CValue::L2CValue(aLStack128,0xfea97fe73);
    lib::L2CValue::L2CValue(aLStack144,0x144e2ef2f8);
    uVar7 = lib::L2CValue::as_integer(aLStack128);
    uVar8 = lib::L2CValue::as_integer(aLStack144);
    fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
    lib::L2CValue::L2CValue(aLStack112,fVar12);
    lib::L2CValue::operator*(aLStack240,aLStack112);
    lib::L2CValue::operator=(aLStack240,aLStack96);
    lib::L2CValue::~L2CValue(aLStack96);
    lib::L2CValue::~L2CValue(aLStack112);
    lib::L2CValue::~L2CValue(aLStack144);
    lib::L2CValue::~L2CValue(aLStack128);
    ppBVar1 = &param_1[2].battleObject;
    pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,0x16);
    lib::L2CValue::L2CValue(aLStack96,SITUATION_KIND_AIR);
    uVar7 = lib::L2CValue::operator==(pLVar9,aLStack96);
    lib::L2CValue::~L2CValue(aLStack96);
    if ((uVar7 & 1) == 0) {
      lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
      lib::L2CValue::L2CValue(aLStack112,0.0);
      lib::L2CAgent::clear_lua_stack(param_1);
      lib::L2CAgent::push_lua_stack(param_1,aLStack96);
      lib::L2CAgent::push_lua_stack(param_1,aLStack240);
      lib::L2CAgent::push_lua_stack(param_1,aLStack112);
      app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
      lib::L2CValue::~L2CValue(aLStack112);
LAB_710000c7a4:
      lib::L2CValue::~L2CValue(aLStack96);
    }
    else {
      lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
      lib::L2CValue::L2CValue(aLStack112,6);
      lib::L2CValue::L2CValue(aLStack128,0.0);
      lib::L2CValue::L2CValue(aLStack144,0.0);
      lib::L2CValue::L2CValue(aLStack160,0.0);
      lib::L2CValue::L2CValue(aLStack176,0.0);
      lib::L2CAgent::clear_lua_stack(param_1);
      lib::L2CAgent::push_lua_stack(param_1,aLStack96);
      lib::L2CAgent::push_lua_stack(param_1,aLStack112);
      lib::L2CAgent::push_lua_stack(param_1,aLStack240);
      lib::L2CAgent::push_lua_stack(param_1,aLStack128);
      lib::L2CAgent::push_lua_stack(param_1,aLStack144);
      lib::L2CAgent::push_lua_stack(param_1,aLStack160);
      lib::L2CAgent::push_lua_stack(param_1,aLStack176);
      app::sv_kinetic_energy::reset_energy(param_1->luaStateAgent);
      lib::L2CValue::~L2CValue(aLStack176);
      lib::L2CValue::~L2CValue(aLStack160);
      lib::L2CValue::~L2CValue(aLStack144);
      lib::L2CValue::~L2CValue(aLStack128);
      lib::L2CValue::~L2CValue(aLStack112);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
      lib::L2CValue::L2CValue(aLStack128,0xfea97fe73);
      lib::L2CValue::L2CValue(aLStack144,0x101d445058);
      uVar7 = lib::L2CValue::as_integer(aLStack128);
      uVar8 = lib::L2CValue::as_integer(aLStack144);
      fVar12 = (float)app::lua_bind::WorkModule__get_param_float_impl(*ppBVar11,uVar7,uVar8);
      lib::L2CValue::L2CValue(aLStack112,fVar12);
      lib::L2CValue::L2CValue(aLStack160,0.0);
      lib::L2CAgent::clear_lua_stack(param_1);
      lib::L2CAgent::push_lua_stack(param_1,aLStack96);
      lib::L2CAgent::push_lua_stack(param_1,aLStack112);
      lib::L2CAgent::push_lua_stack(param_1,aLStack160);
      app::sv_kinetic_energy::set_brake(param_1->luaStateAgent);
      lib::L2CValue::~L2CValue(aLStack160);
      lib::L2CValue::~L2CValue(aLStack112);
      lib::L2CValue::~L2CValue(aLStack144);
      lib::L2CValue::~L2CValue(aLStack128);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_STOP);
      iVar4 = lib::L2CValue::as_integer(aLStack96);
      app::lua_bind::KineticModule__enable_energy_impl(*ppBVar11,iVar4);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::L2CValue(aLStack128,0xfea97fe73);
      lib::L2CValue::L2CValue(aLStack144,0x15d86ad648);
      uVar7 = lib::L2CValue::as_integer(aLStack128);
      uVar8 = lib::L2CValue::as_integer(aLStack144);
      iVar4 = app::lua_bind::WorkModule__get_param_int_impl(*ppBVar11,uVar7,uVar8);
      lib::L2CValue::L2CValue(aLStack112,iVar4);
      lib::L2CValue::L2CValue(aLStack96,0);
      uVar7 = lib::L2CValue::operator==(aLStack112,aLStack96);
      lib::L2CValue::~L2CValue(aLStack96);
      lib::L2CValue::~L2CValue(aLStack112);
      lib::L2CValue::~L2CValue(aLStack144);
      lib::L2CValue::~L2CValue(aLStack128);
      if ((uVar7 & 1) == 0) {
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        lib::L2CValue::L2CValue(aLStack112,0.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack112);
        app::sv_kinetic_energy::set_speed(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack112);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        lib::L2CValue::L2CValue(aLStack112,0.0);
        lib::L2CAgent::clear_lua_stack(param_1);
        lib::L2CAgent::push_lua_stack(param_1,aLStack96);
        lib::L2CAgent::push_lua_stack(param_1,aLStack112);
        app::sv_kinetic_energy::set_accel(param_1->luaStateAgent);
        lib::L2CValue::~L2CValue(aLStack112);
        lib::L2CValue::~L2CValue(aLStack96);
        lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
        iVar4 = lib::L2CValue::as_integer(aLStack96);
        app::lua_bind::KineticModule__enable_energy_impl(*ppBVar11,iVar4);
        goto LAB_710000c7a4;
      }
    }
    lib::L2CValue::L2CValue(aLStack96,_FIGHTER_KINETIC_ENERGY_ID_CONTROL);
    pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,5);
    iVar4 = lib::L2CValue::as_integer(aLStack96);
    pBVar10 = (BattleObjectModuleAccessor *)lib::L2CValue::as_pointer(pLVar9);
    app::KineticUtility::clear_unable_energy(iVar4,pBVar10);
    lib::L2CValue::~L2CValue(aLStack96);
    lib::L2CValue::L2CValue(aLStack96,FIGHTER_KINETIC_ENERGY_ID_MOTION);
    pLVar9 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)ppBVar1,5);
    iVar4 = lib::L2CValue::as_integer(aLStack96);
    pBVar10 = (BattleObjectModuleAccessor *)lib::L2CValue::as_pointer(pLVar9);
    app::KineticUtility::clear_unable_energy(iVar4,pBVar10);
LAB_710000c82c:
    pLVar9 = aLStack96;
  }
  lib::L2CValue::~L2CValue(pLVar9);
LAB_710000c848:
  lib::L2CValue::~L2CValue(aLStack256);
  lib::L2CValue::~L2CValue(aLStack240);
  lib::L2CValue::~L2CValue(aLStack224);
  return;
}

