
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_7100011ab0(L2CAgentBase *param_1)

{
  L2CValue aLStack64 [16];
  L2CValue aLStack48 [16];
  
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ENTRY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Entry_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ENTRY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Entry_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ENTRY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Entry_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_STANDBY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Standby_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_STANDBY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Standby_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_STANDBY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Standby_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_REBIRTH);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Rebirth_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_REBIRTH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Rebirth_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_REBIRTH);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Rebirth_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DEAD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Dead_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DEAD);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Dead_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DEAD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Dead_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_WARP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Warp_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_WARP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Warp_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_WARP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Warp_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DEMO);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Demo_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DEMO);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Demo_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DEMO);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Demo_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DRAGOON);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Dragoon_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DRAGOON);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Dragoon_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DRAGOON);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Dragoon_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_100);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack100_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_100);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack100_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_100);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack100_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_100_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack100End_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_100_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack100End_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_100_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack100End_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_DASH);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::AttackDash_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_DASH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::AttackDash_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_DASH);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::AttackDash_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_AIR);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::AttackAir_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_AIR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::AttackAir_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_AIR);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::AttackAir_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_3);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack3_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_3);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack3_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_3);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack3_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4_START);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4Start_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4_START);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4Start_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4_START);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4Start_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4_HOLD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4Hold_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4_HOLD);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4Hold_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4_HOLD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4Hold_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_ATTACK_4);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Attack4_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Damage_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Damage_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Damage_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_AIR);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageAir_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_AIR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageAir_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_AIR);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageAir_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_LR);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectLr_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_LR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectLr_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_LR);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectLr_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_U);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectU_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_U);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectU_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_U);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectU_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FALL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FALL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FALL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DOWN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Down_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DOWN);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Down_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DOWN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Down_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Follow_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Follow_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Follow_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowTurn_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_TURN);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowTurn_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowTurn_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_GUARD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowGuard_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_GUARD);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowGuard_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_GUARD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowGuard_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_WORRY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowWorry_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_WORRY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowWorry_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_WORRY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowWorry_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_HAPPY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowHappy_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_HAPPY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowHappy_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_HAPPY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowHappy_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_APPEAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowAppeal_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_APPEAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowAppeal_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FOLLOW_APPEAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FollowAppeal_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_WAIT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeWait_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_WAIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeWait_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_WAIT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeWait_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_GROUND_MOVE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeGroundMove_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_GROUND_MOVE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeGroundMove_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_GROUND_MOVE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeGroundMove_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_BRAKE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeBrake_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_BRAKE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeBrake_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_BRAKE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeBrake_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_JUMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeJump_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_JUMP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeJump_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_JUMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeJump_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_JUMP_SQUAT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeJumpSquat_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_JUMP_SQUAT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeJumpSquat_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_JUMP_SQUAT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeJumpSquat_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_FALL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeFall_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_FALL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeFall_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_FALL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeFall_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_LANDING);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeLanding_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeLanding_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_LANDING);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeLanding_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeTurn_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_TURN);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeTurn_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_TURN);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeTurn_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_GUARD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeGuard_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_GUARD);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeGuard_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_GUARD);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeGuard_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_WORRY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeWorry_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_WORRY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeWorry_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_WORRY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeWorry_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_HAPPY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeHappy_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_HAPPY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeHappy_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_HAPPY);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeHappy_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_APPEAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeAppeal_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_APPEAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeAppeal_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FREE_APPEAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::FreeAppeal_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_START);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNStart_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_START);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNStart_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_START);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNStart_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_CHARGE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNCharge_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_CHARGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNCharge_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_CHARGE);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNCharge_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_SHOOT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNShoot_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_SHOOT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNShoot_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_SHOOT);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNShoot_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNEnd_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_N_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialNEnd_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialS_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialS_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_S);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialS_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_START);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiStart_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_START);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiStart_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_START);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiStart_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_JUMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiJump_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_JUMP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiJump_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_JUMP);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiJump_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiEnd_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_HI_END);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialHiEnd_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialLw_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialLw_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_SPECIAL_LW);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::SpecialLw_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_PRE);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Final_pre);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Final_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,_LUA_SCRIPT_STATUS_FUNC_STATUS_END);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::Final_end);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_AIR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_LR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectLr_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_U);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_INIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectU_init);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_AIR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFly_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_LR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectU_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_U);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXEC_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFlyReflectU_exec);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_AIR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_LR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FLY_REFLECT_U);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_WEAPON_ROSETTA_TICO_STATUS_KIND_DAMAGE_FALL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_EXIT_STATUS);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CWeaponRosettaTico::status::DamageFall_exit);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  return;
}

