
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_710001a820(L2CAgent *param_1,L2CValue *param_2,L2CValue *param_3,L2CValue *param_4,
                   L2CValue *param_5)

{
  byte bVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  Hash40 HVar5;
  ulong uVar6;
  ulong uVar7;
  L2CValue *pLVar8;
  BattleObjectModuleAccessor *pBVar9;
  float fVar10;
  float fVar11;
  L2CValue aLStack320 [16];
  L2CValue aLStack304 [16];
  L2CValue aLStack288 [16];
  L2CValue aLStack272 [16];
  L2CValue aLStack256 [16];
  L2CValue aLStack240 [16];
  undefined auStack224 [32];
  L2CValue aLStack192 [16];
  undefined auStack176 [32];
  L2CValue aLStack144 [16];
  undefined8 local_80;
  BattleObject *pBStack120;
  BattleObjectModuleAccessor *pBStack112;
  undefined8 uStack104;
  
  lib::L2CValue::L2CValue
            ((L2CValue *)&pBStack112,_FIGHTER_RIDLEY_STATUS_SPECIAL_HI_FLAG_CHARGE_DECCEL);
  iVar2 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  app::lua_bind::WorkModule__off_flag_impl(param_1->moduleAccessor,iVar2);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,0);
  lib::L2CValue::L2CValue
            ((L2CValue *)&local_80,_FIGHTER_RIDLEY_STATUS_SPECIAL_HI_WORK_INT_CHARGE_COUNT);
  iVar2 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  iVar3 = lib::L2CValue::as_integer((L2CValue *)&local_80);
  app::lua_bind::WorkModule__set_int_impl(param_1->moduleAccessor,iVar2,iVar3);
  lib::L2CValue::~L2CValue((L2CValue *)&local_80);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,0.0);
  lib::L2CValue::L2CValue((L2CValue *)&local_80,1.0);
  lib::L2CValue::L2CValue(aLStack144,false);
  HVar5 = lib::L2CValue::as_hash(param_2);
  fVar10 = (float)lib::L2CValue::as_number((L2CValue *)&pBStack112);
  fVar11 = (float)lib::L2CValue::as_number((L2CValue *)&local_80);
  bVar1 = lib::L2CValue::as_bool(aLStack144);
  app::lua_bind::MotionModule__change_motion_impl
            (param_1->moduleAccessor,HVar5,fVar10,fVar11,(bool)(bVar1 & 1),0.0,false,false);
  lib::L2CValue::~L2CValue(aLStack144);
  lib::L2CValue::~L2CValue((L2CValue *)&local_80);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,0x1086bc4a93);
  uVar6 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  uVar7 = lib::L2CValue::as_integer(param_3);
  iVar2 = app::lua_bind::WorkModule__get_param_int_impl(param_1->moduleAccessor,uVar6,uVar7);
  lib::L2CValue::L2CValue(aLStack144,iVar2);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  uVar4 = app::lua_bind::MotionModule__end_frame_impl(param_1->moduleAccessor);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,uVar4);
  lib::L2CValue::operator/((L2CValue *)&pBStack112,aLStack144);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  fVar10 = (float)lib::L2CValue::as_number((L2CValue *)(auStack176 + 0x10));
  app::lua_bind::MotionModule__set_rate_impl(param_1->moduleAccessor,fVar10);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_STOP);
  iVar2 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  app::lua_bind::KineticModule__enable_energy_impl(param_1->moduleAccessor,iVar2);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,FIGHTER_KINETIC_ENERGY_ID_MOTION);
  iVar2 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  app::lua_bind::KineticModule__unable_energy_impl(param_1->moduleAccessor,iVar2);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,FIGHTER_KINETIC_ENERGY_ID_GRAVITY);
  iVar2 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  app::lua_bind::KineticModule__unable_energy_impl(param_1->moduleAccessor,iVar2);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_CONTROL);
  iVar2 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  app::lua_bind::KineticModule__unable_energy_impl(param_1->moduleAccessor,iVar2);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,0x1086bc4a93);
  uVar6 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  uVar7 = lib::L2CValue::as_integer(param_4);
  fVar10 = (float)app::lua_bind::WorkModule__get_param_float_impl
                            (param_1->moduleAccessor,uVar6,uVar7);
  lib::L2CValue::L2CValue((L2CValue *)auStack176,fVar10);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,0x1086bc4a93);
  pLVar8 = (L2CValue *)lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  uVar6 = lib::L2CValue::as_integer(param_5);
  fVar10 = (float)app::lua_bind::WorkModule__get_param_float_impl
                            (param_1->moduleAccessor,(ulong)pLVar8,uVar6);
  lib::L2CValue::L2CValue(aLStack192,fVar10);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  fVar10 = (float)app::lua_bind::PostureModule__lr_impl(param_1->moduleAccessor);
  lib::L2CValue::L2CValue((L2CValue *)(auStack224 + 0x10),fVar10);
  lib::L2CAgent::math_rad((L2CAgent *)auStack176,pLVar8);
  lib::L2CAgent::math_cos((L2CAgent *)auStack224,pLVar8);
  lib::L2CValue::operator*(aLStack192,(L2CValue *)&local_80);
  pLVar8 = (L2CValue *)(auStack224 + 0x10);
  lib::L2CValue::operator*((L2CValue *)&pBStack112,pLVar8);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::~L2CValue((L2CValue *)&local_80);
  lib::L2CAgent::math_sin((L2CAgent *)auStack224,pLVar8);
  lib::L2CValue::operator*(aLStack192,(L2CValue *)&pBStack112);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_STOP);
  lib::L2CValue::L2CValue((L2CValue *)&local_80,ENERGY_STOP_RESET_TYPE_AIR);
  lib::L2CValue::L2CValue(aLStack272,0.0);
  lib::L2CValue::L2CValue(aLStack288,0.0);
  lib::L2CValue::L2CValue(aLStack304,0.0);
  lib::L2CAgent::clear_lua_stack(param_1);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&pBStack112);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&local_80);
  lib::L2CAgent::push_lua_stack(param_1,aLStack240);
  lib::L2CAgent::push_lua_stack(param_1,aLStack256);
  lib::L2CAgent::push_lua_stack(param_1,aLStack272);
  lib::L2CAgent::push_lua_stack(param_1,aLStack288);
  lib::L2CAgent::push_lua_stack(param_1,aLStack304);
  app::sv_kinetic_energy::reset_energy(param_1->luaStateAgent);
  lib::L2CValue::~L2CValue(aLStack304);
  lib::L2CValue::~L2CValue(aLStack288);
  lib::L2CValue::~L2CValue(aLStack272);
  lib::L2CValue::~L2CValue((L2CValue *)&local_80);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_STOP);
  lib::L2CValue::L2CValue((L2CValue *)&local_80,0.0);
  lib::L2CValue::L2CValue(aLStack272,0.0);
  lib::L2CAgent::clear_lua_stack(param_1);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&pBStack112);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&local_80);
  lib::L2CAgent::push_lua_stack(param_1,aLStack272);
  app::sv_kinetic_energy::set_accel(param_1->luaStateAgent);
  lib::L2CValue::~L2CValue(aLStack272);
  lib::L2CValue::~L2CValue((L2CValue *)&local_80);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_STOP);
  lib::L2CValue::L2CValue((L2CValue *)&local_80,0.0);
  lib::L2CValue::L2CValue(aLStack272,0.0);
  lib::L2CAgent::clear_lua_stack(param_1);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&pBStack112);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&local_80);
  lib::L2CAgent::push_lua_stack(param_1,aLStack272);
  app::sv_kinetic_energy::set_brake(param_1->luaStateAgent);
  lib::L2CValue::~L2CValue(aLStack272);
  lib::L2CValue::~L2CValue((L2CValue *)&local_80);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_STOP);
  lib::L2CAgent::clear_lua_stack(param_1);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&pBStack112);
  lib::L2CAgent::push_lua_stack(param_1,aLStack240);
  lib::L2CAgent::push_lua_stack(param_1,aLStack256);
  app::sv_kinetic_energy::set_limit_speed(param_1->luaStateAgent);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_STOP);
  lib::L2CAgent::clear_lua_stack(param_1);
  lib::L2CAgent::push_lua_stack(param_1,(L2CValue *)&pBStack112);
  lib::L2CAgent::push_lua_stack(param_1,aLStack240);
  lib::L2CAgent::push_lua_stack(param_1,aLStack256);
  app::sv_kinetic_energy::set_stable_speed(param_1->luaStateAgent);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue((L2CValue *)&pBStack112,_FIGHTER_KINETIC_ENERGY_ID_STOP);
  iVar2 = lib::L2CValue::as_integer((L2CValue *)&pBStack112);
  app::lua_bind::KineticModule__unable_energy_impl(param_1->moduleAccessor,iVar2);
  lib::L2CValue::~L2CValue((L2CValue *)&pBStack112);
  lib::L2CValue::L2CValue(aLStack272,FIGHTER_KINETIC_ENERGY_ID_MOTION);
  pLVar8 = (L2CValue *)lib::L2CValue::operator[]((L2CValue *)&param_1[2].battleObject,5);
  lib::L2CValue::L2CValue(aLStack288,_ENERGY_MOTION_RESET_TYPE_AIR_TRANS);
  lib::L2CValue::L2CValue(aLStack304,0.0);
  lib::L2CValue::L2CValue(aLStack320,0.0);
  iVar2 = lib::L2CValue::as_integer(aLStack272);
  pBVar9 = (BattleObjectModuleAccessor *)lib::L2CValue::as_pointer(pLVar8);
  iVar3 = lib::L2CValue::as_integer(aLStack288);
  uVar6 = lib::L2CValue::as_number(aLStack304);
  uVar4 = lib::L2CValue::as_number(aLStack320);
  pBStack112 = (BattleObjectModuleAccessor *)(uVar6 & 0xffffffff | (ulong)uVar4 << 0x20);
  pBStack120 = LUA_SCRIPT_LINE_MAP_CORRECTION;
  local_80 = LUA_SCRIPT_LINE_STATUS_SHIFT;
  uStack104 = 0;
  app::KineticUtility::reset_enable_energy
            (iVar2,pBVar9,iVar3,(Vector2f *)&pBStack112,(Vector3f *)&local_80);
  lib::L2CValue::~L2CValue(aLStack320);
  lib::L2CValue::~L2CValue(aLStack304);
  lib::L2CValue::~L2CValue(aLStack288);
  lib::L2CValue::~L2CValue(aLStack272);
  lib::L2CValue::~L2CValue(aLStack256);
  lib::L2CValue::~L2CValue(aLStack240);
  lib::L2CValue::~L2CValue((L2CValue *)auStack224);
  lib::L2CValue::~L2CValue((L2CValue *)(auStack224 + 0x10));
  lib::L2CValue::~L2CValue(aLStack192);
  lib::L2CValue::~L2CValue((L2CValue *)auStack176);
  lib::L2CValue::~L2CValue((L2CValue *)(auStack176 + 0x10));
  lib::L2CValue::~L2CValue(aLStack144);
  return;
}

