
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_7100013350(L2CAgentBase *param_1)

{
  L2CValue aLStack64 [16];
  L2CValue aLStack48 [16];
  
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_WAIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Wait_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_WALK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Walk_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_WALK_BRAKE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::WalkBrake_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_JUMP_SQUAT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::JumpSquat_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_JUMP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Jump_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_JUMP_AERIAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::JumpAerial_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_ITEM_SCREW_JUMP_AERIAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::ItemScrewJumpAerial_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_SQUAT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Squat_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SQUAT_WAIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SquatWait_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SQUAT_RV);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SquatRv_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_PASS);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Pass_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_FALL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Fall_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_FALL_AERIAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::FallAerial_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Landing_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_LANDING_LIGHT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::LandingLight_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_REBOUND_STOP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::ReboundStop_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_ATTACK_100);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Attack100_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_ATTACK_AIR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackAir_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_LADDER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Ladder_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_LADDER_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::LadderAttack_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_GIMMICK_DRUM);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::GimmickDrum_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_FINAL_VISUAL_ATTACK_OTHER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::FinalVisualAttackOther_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_WAIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackWait_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_WALK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackWalk_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_WALK_BRAKE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackWalkBrake_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_WALK_BACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackWalkBack_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_WALK_BRAKE_BACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackWalkBrakeBack_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_JUMP_SQUAT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackJumpSquat_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_JUMP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackJump_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_JUMP_AERIAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackJumpAerial_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_FALL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackFall_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_FALL_AERIAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackFallAerial_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackLanding_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_LANDING_LIGHT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackLandingLight_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_SQUAT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackSquat_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_SQUAT_WAIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackSquatWait_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_SQUAT_RV);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackSquatRv_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_LADDER);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackLadder_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_ATTACK_COMBO);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AttackCombo_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_CATCH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Catch_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_CATCH_DASH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchDash_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_CATCH_TURN);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchTurn_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_CATCH_PULL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchPull_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_CATCH_DASH_PULL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchDashPull_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_CATCH_WAIT);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchWait_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_CATCH_ATTACK);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchAttack_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_CATCH_PHYSICS_REWIND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchPhysicsRewind_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_CATCH_PHYSICS_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::CatchPhysicsEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_SPECIAL_HI);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SpecialHi_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_SPECIAL_HI_GROUND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SpecialHiGround_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_SPECIAL_HI_GROUND_JUMP);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SpecialHiGroundJump_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_SPECIAL_HI_GROUND_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SpecialHiGroundEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_SPECIAL_HI_AIR);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SpecialHiAir_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_SPECIAL_HI_AIR_REACH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SpecialHiAirReach_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_SPECIAL_HI_AIR_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::SpecialHiAirEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_AIR_LASSO_REACH);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AirLassoReach_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_STATUS_KIND_AIR_LASSO_HANG);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AirLassoHang_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_AIR_LASSO_REWIND);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AirLassoRewind_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_AIR_LASSO_FAILURE);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AirLassoFailure_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_AIR_LASSO_LANDING);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::AirLassoLanding_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,FIGHTER_STATUS_KIND_FINAL);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::Final_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_FINAL_READY);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::FinalReady_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_FINAL_SCENE01);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::FinalScene01_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_FINAL_SCENE02);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::FinalScene02_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_FINAL_SCENE03);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::FinalScene03_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  lib::L2CValue::L2CValue(aLStack48,_FIGHTER_TANTAN_STATUS_KIND_FINAL_END);
  lib::L2CValue::L2CValue(aLStack64,LUA_SCRIPT_STATUS_FUNC_STATUS_MAIN);
  lua2cpp::L2CAgentBase::sv_set_status_func
            (param_1,aLStack48,aLStack64,L2CFighterTantan::status::FinalEnd_main);
  lib::L2CValue::~L2CValue(aLStack64);
  lib::L2CValue::~L2CValue(aLStack48);
  return;
}

